#!/bin/bash
echo &quot;========================================= Deploying to test host ===========================================&quot;
sleep 60
cd build

sudo -u deployify /usr/share/spotify-deployment-scripts/scripts/deploy/deploy.sh spotify-deployment-scripts /usr/share/spotify-deployment-scripts/etc/services/deployment_scripts.json testing all `cat pkg-version.txt`
sudo -u deployify /usr/share/spotify-deployment-scripts/scripts/deploy/deploy.sh spotify-deployment-scripts-systest /usr/share/spotify-deployment-scripts/etc/services/deployment_scripts.json testing all `cat pkg-version.txt`
